### ISSUE TITLE
Cannot use it with 11 java because of error: option -Xbootclasspath/p: not allowed with target 11

### ISSUE THREAD

**Issue by comdiv** [boothen/gradle-wsimport#6] opened 2019-06-10 07:19 UTC
It's reproduced if it's used with OJDK 11 as build platform

**Comment by boothen** [comment] 2019-06-10 21:00
Hi @comdiv ,

Thanks for reporting the issue. Could you provide more information about the issue, such as an example of the build.gradle file or command line args?

Thanks.

**Comment by jvs64893** [comment] 2019-08-05 14:53
I can confirm this error. You basically only need a Gradle project using JDK 11 and this issue already triggers:
`error: option -Xbootclasspath/p: not allowed with target 11`

This is the accompanying stack trace:
```
Caused by: wsimport failed
        at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:432)
        at com.sun.tools.ws.ant.WsImport2.execute(WsImport2.java:558)
        at uk.co.boothen.gradle.wsimport.WsImportRunnable.run(WsImportRunnable.java:73)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:41)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:34)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.execute(IsolatedClassloaderWorker.java:55)
        at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1$1.execute(IsolatedClassloaderWorkerFactory.java:46)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.execute(IsolatedClassloaderWorkerFactory.java:42)
        at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:107)
        at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:101)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        ... 3 more
```

**Comment by boothen** [comment] 2019-08-06 15:28
Hi @jvs64893,

Is this the Oracle JDK rather than OpenJDK? I can't reproduce the issue with OpenJDK 11.

Thanks.

**Comment by jvs64893** [comment] 2019-08-07 07:25
@boothen 
No, I'm using OpenJDK 11 as well. Precisely I'm using AdoptOpenJDK 11.0.4+11.2 64 Bit on Windows x64. This is the latest OpenJDK 11 release.

edit:
I tried around some more and got it working by setting `xnocompile = true`. The generation succeeds and you can just compile it afterwards.

The issue should still be looked into anyway.

**Comment by boothen** [comment] 2019-08-07 15:22
Thanks for the details. Makes sense as I've been using the plugin with OpenJDK 11, but it's been set to xnocompile = true.

I'll take a look at what can be done to fix it.

**Comment by boothen** [comment] 2019-08-08 07:25
@jvs64893 sorry about this. I'm still struggling to reproduce the issue. Could you send me the details of the configuration you're using? Plus the plugin and Gradle version? 

I've noticed the README was out of date. It stated to use version 0.7 of the plugin, but there's a 0.9 that may have resolved this issue.

**Comment by jvs64893** [comment] 2019-08-08 07:39
@boothen 
That did the trick! My version was set to 0.7 as per README, using 0.9 everything works perfectly fine.

I guess you can close this issue now.

**Comment by boothen** [comment] 2019-08-08 07:42
Great! Sorry about the confusion. I'll see if there's a better way to keep all the version numbers in sync.

**Closed as completed by boothen** 2019-08-08 07:42 UTC
